### ISSUE TITLE
Error with icpc OpenMP compilation

### ISSUE THREAD

**Issue by mcuma** [cran/ModelMetrics#2]
Intel's icpc when using -qopenmp flag is throwing errors as:
error.cpp(17): error: (END-BEGIN) must return an integer type in parallel loop
    for(int i = 0; i < Rows; ++i) {
                   ^

This is due to the loop maximum value Rows being a double, while it needs to be an int. It can be fixed with a cast:
    for(int i = 0; i < (int)Rows; ++i) {

The same error also occurs in two places in auc_.cpp.

**Comment by gaborcsardi** [comment]
Hi, this is a read-only mirror of CRAN, please contact the package authors, see the DESCRIPTION file.

**Comment by mcuma** [comment]
Got it, thanks.
